# Generated by Django 4.2.1 on 2023-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_movie_popularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="popularity",
            field=models.IntegerField(default=5),
        ),
    ]
