# Generated by Django 4.2.1 on 2023-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_movie_popularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=130),
        ),
    ]
