# Generated by Django 4.2.1 on 2023-06-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_cart_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="name",
            field=models.CharField(max_length=130),
        ),
    ]
