# Generated by Django 4.2.1 on 2023-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_bill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="Flat_House_no_Building_Company_Apartment",
            new_name="Apartment_or_Building_number",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="Area_Street_Sector_Village",
            new_name="Area_or_street",
        ),
        migrations.AlterField(
            model_name="bill",
            name="mobile_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="bill",
            name="state",
            field=models.CharField(
                choices=[
                    ("Andhra Pradesh", " x"),
                    ("Arunachal Pradesh ", " x"),
                    ("Assam", " x"),
                    ("Bihar", " x"),
                    ("Chhattisgarh", " x"),
                    ("Goa", " x"),
                    ("Gujarat", " x"),
                    ("Haryana", " x"),
                    ("Himachal Pradesh", " x"),
                    ("Jammu and Kashmir", " x"),
                    ("Jharkhand", " x"),
                    ("Karnataka", " x"),
                    ("Kerala", " x"),
                    ("Madhya Pradesh", " x"),
                    ("Maharashtra", " x"),
                    ("Manipur", " x"),
                    ("Meghalaya", " x"),
                    ("Mizoram", " x"),
                    ("Nagaland", " x"),
                    ("Odisha", " x"),
                    ("Punjab", " x"),
                    ("Rajasthan", " x"),
                    ("Sikkim", " x"),
                    ("Tamil Nadu", " x"),
                    ("Telangana", " x"),
                    ("Tripura", " x"),
                    ("Uttar Pradesh", " x"),
                    ("Uttarakhand", " x"),
                    ("West Bengal", " x"),
                    ("Andaman and Nicobar Islands", " x"),
                    ("Chandigarh", " x"),
                    ("Dadra and Nagar Haveli", " x"),
                    ("Daman and Diu", " x"),
                    ("Lakshadweep", " x"),
                    ("National Capital Territory of Delhi", " x"),
                    ("Puducherry", " x"),
                ],
                max_length=50,
            ),
        ),
    ]
