# Generated by Django 4.2.1 on 2023-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0011_rename_flat_house_no_building_company_apartment_bill_apartment_or_building_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="pincode",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="bill",
            name="state",
            field=models.CharField(
                choices=[
                    ("Andhra Pradesh", " Andhra Pradesh"),
                    ("Arunachal Pradesh ", " Arunachal Pradesh "),
                    ("Assam", " Assam"),
                    ("Bihar", " Bihar"),
                    ("Chhattisgarh", " Chhattisgarh"),
                    ("Goa", " Goa"),
                    ("Gujarat", " Gujarat"),
                    ("Haryana", " Haryana"),
                    ("Himachal Pradesh", " Himachal Pradesh"),
                    ("Jammu and Kashmir", " Jammu and Kashmir"),
                    ("Jharkhand", " Jharkhand"),
                    ("Karnataka", " Karnataka"),
                    ("Kerala", " Kerala"),
                    ("Madhya Pradesh", " Madhya Pradesh"),
                    ("Maharashtra", " Maharashtra"),
                    ("Manipur", " Manipur"),
                    ("Meghalaya", " Meghalaya"),
                    ("Mizoram", " Mizoram"),
                    ("Nagaland", " Nagaland"),
                    ("Odisha", " Odisha"),
                    ("Punjab", " Punjab"),
                    ("Rajasthan", " Rajasthan"),
                    ("Sikkim", " Sikkim"),
                    ("Tamil Nadu", " Tamil Nadu"),
                    ("Telangana", " Telangana"),
                    ("Tripura", " Tripura"),
                    ("Uttar Pradesh", " Uttar Pradesh"),
                    ("Uttarakhand", " Uttarakhand"),
                    ("West Bengal", " West Bengal"),
                    ("Andaman and Nicobar Islands", " Andaman and Nicobar Islands"),
                    ("Chandigarh", " Chandigarh"),
                    ("Dadra and Nagar Haveli", " Dadra and Nagar Haveli"),
                    ("Daman and Diu", " Daman and Diu"),
                    ("Lakshadweep", " Lakshadweep"),
                    (
                        "National Capital Territory of Delhi",
                        " National Capital Territory of Delhi",
                    ),
                    ("Puducherry", " Puducherry"),
                ],
                max_length=50,
            ),
        ),
    ]
